version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment: &db_env
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_HOST: db
    ports:
      - "9906:3306"
  nginx:
    image: nginx
    restart: always
    volumes:
      - "./etc/nginx/conf.d:/etc/nginx/conf.d"
      - "./src:/var/www/html"
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    build: ./dockerfiles/php
    container_name: php_72
    environment: *db_env
    restart: always
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - db